In [1]:
#importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()

In [2]:
#Collegamento al Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

#Sklearn

In [3]:
with open("/content/drive/MyDrive/KPMG/RegressionDataset.xlsx", 'rb') as fp:
    df = pd.read_excel(fp)

In [4]:
df

,AnnoAccademico,Ateneo,PopolazioneP,AteneiP,PopolazioneR,AteneiR,Fuorisede,Immatricolati
0,2010/2011,Aosta,126957,1,126957,1,31,188
1,2011/2012,Aosta,127153,1,127153,1,21,172
2,2012/2013,Aosta,127305,1,127305,1,31,173
3,2013/2014,Aosta,127951,1,127951,1,54,192
4,2014/2015,Aosta,128245,1,128245,1,52,181
...,...,...,...,...,...,...,...,...
644,2016/2017,Verona,918050,1,4890648,4,2509,4553
645,2017/2018,Verona,918069,1,4883373,4,2477,4484
646,2018/2019,Verona,919179,1,4880936,4,2098,3874
647,2019/2020,Verona,922857,1,4884590,4,2082,3785
648,2020/2021,Verona,927108,1,4870000,4,2547,4718

In [5]:
df1=df

In [6]:
categorical_cols=df.columns[df.dtypes==object].tolist()
categorical_cols

['AnnoAccademico', 'Ateneo']

In [7]:
from sklearn.preprocessing import OneHotEncoder

#creating instance of one-hot-encoder
encoder = OneHotEncoder(handle_unknown='ignore')

#perform one-hot encoding on 'team' column 
encoder_df = pd.DataFrame(encoder.fit_transform(df[['Ateneo']]).toarray())

#merge one-hot encoded columns back with original DataFrame
final_df = df.join(encoder_df)

#view final df
print(final_df)

    AnnoAccademico  Ateneo  PopolazioneP  AteneiP  PopolazioneR  AteneiR  \
0        2010/2011   Aosta        126957        1        126957        1
1        2011/2012   Aosta        127153        1        127153        1
2        2012/2013   Aosta        127305        1        127305        1
3        2013/2014   Aosta        127951        1        127951        1
4        2014/2015   Aosta        128245        1        128245        1
..             ...     ...           ...      ...           ...      ...
644      2016/2017  Verona        918050        1       4890648        4
645      2017/2018  Verona        918069        1       4883373        4
646      2018/2019  Verona        919179        1       4880936        4
647      2019/2020  Verona        922857        1       4884590        4
648      2020/2021  Verona        927108        1       4870000        4

     Fuorisede  Immatricolati    0    1  ...   49   50   51   52   53   54  \
0           31            188  1.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
1           21            172  1.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
2           31            173  1.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
3           54            192  1.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
4           52            181  1.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
..         ...            ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
644       2509           4553  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
645       2477           4484  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
646       2098           3874  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
647       2082           3785  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
648       2547           4718  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0

      55   56   57   58
0    0.0  0.0  0.0  0.0
1    0.0  0.0  0.0  0.0
2    0.0  0.0  0.0  0.0
3    0.0  0.0  0.0  0.0
4    0.0  0.0  0.0  0.0
..   ...  ...  ...  ...
644  0.0  0.0  0.0  1.0
645  0.0  0.0  0.0  1.0
646  0.0  0.0  0.0  1.0
647  0.0  0.0  0.0  1.0
648  0.0  0.0  0.0  1.0

[649 rows x 67 columns]

In [8]:
df=final_df

In [9]:
df["AnnoAccademico"]=df["AnnoAccademico"].astype('category').cat.codes
#df["AteneoNOME"]=df["AteneoNOME"].astype('category').cat.codes

In [10]:
df=df.drop(columns=['Ateneo'])

In [11]:
df

,AnnoAccademico,PopolazioneP,AteneiP,PopolazioneR,AteneiR,Fuorisede,Immatricolati,0,1,2,...,49,50,51,52,53,54,55,56,57,58
0,0,126957,1,126957,1,31,188,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,127153,1,127153,1,21,172,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,127305,1,127305,1,31,173,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,127951,1,127951,1,54,192,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,128245,1,128245,1,52,181,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,6,918050,1,4890648,4,2509,4553,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
645,7,918069,1,4883373,4,2477,4484,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
646,8,919179,1,4880936,4,2098,3874,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
647,9,922857,1,4884590,4,2082,3785,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
648,11,927108,1,4870000,4,2547,4718,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [12]:
df = df.fillna(0)

In [13]:
df = df.astype({'Fuorisede': int})

In [14]:
df.columns

Index(['AnnoAccademico',   'PopolazioneP',        'AteneiP',   'PopolazioneR',
              'AteneiR',      'Fuorisede',  'Immatricolati',                0,
                      1,                2,                3,                4,
                      5,                6,                7,                8,
                      9,               10,               11,               12,
                     13,               14,               15,               16,
                     17,               18,               19,               20,
                     21,               22,               23,               24,
                     25,               26,               27,               28,
                     29,               30,               31,               32,
                     33,               34,               35,               36,
                     37,               38,               39,               40,
                     41,               42,               43,               44,
                     45,               46,               47,               48,
                     49,               50,               51,               52,
                     53,               54,               55,               56,
                     57,               58],
      dtype='object')

In [15]:
X=df.drop(columns=['Immatricolati'])
Y=df["Immatricolati"]

In [16]:
#Split the Training 75% and 25% Testing
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, random_state=0)

In [17]:
#Split the Training 75% and Validation 25%
from sklearn.model_selection import train_test_split

X_train, X_validation, Y_train, Y_validation = train_test_split(X_train, Y_train, test_size=0.25, random_state=0)

In [18]:
#Scale the data (Feature Scaling Z Score) z = (x - u) / s
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train = sc.fit_transform(X_train)
X_validation=sc.transform(X_validation)
X_test = sc.transform(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,

In [19]:
X_train = np.array(X_train)
X_validation=np.array(X_validation)
X_test = np.array(X_test)

Y_train = np.array(Y_train)
Y_validation=np.array(Y_validation)
Y_test = np.array(Y_test)

#RandomForest Regressor

In [49]:
import time
start = time.time()

from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators=1000,max_depth=3, random_state=0) 

regressor.fit(X_train,Y_train)

end = time.time()
print(format(end-start))

1.5767450332641602

In [50]:
# test the output by changing values, like 3750
y_pred = regressor.predict(X_validation)
  
# print the predicted price
print("Predicted Immatricolazioni:")
print(y_pred)

Predicted Immatricolazioni:
[ 6758.89404872  1282.17885962  8976.28280592  1224.9703451
  1282.17885962  3460.23873232  8963.64448665  1282.17885962
  3395.09768615  4740.8507785   4573.58764836 11216.45548002
  3403.94572716 11307.85351368  4730.15849095  1282.17885962
  3642.08752171  1282.17885962  7615.4796381   8650.62794311
  4776.80069731  1282.17885962  1282.17885962  1277.12406128
  4412.18085485  1226.36416262  3846.01555256  3405.66207255
  4629.91386092  1282.17885962  4918.23219331  8673.05405028
  3204.40977231  7204.25264698  1277.12406128  1277.12406128
  1282.17885962  1282.17885962 11321.34098843  9120.05070655
  1282.17885962  1282.17885962  1282.17885962  1340.39311591
  1293.68495147  1282.17885962  1264.75899287 11189.76094951
  3554.41497587  1282.17885962  3403.94572716  4832.90145369
  3403.94572716  1289.79056716  1282.17885962  1282.17885962
  1282.17885962 13839.65988313  3460.23873232  1282.17885962
  4720.29819206  1230.02514344  4675.58212276  3405.66207255
  4776.80069731  8746.0090619  14001.76844314  4691.83723672
  3923.11054764  1282.17885962  1282.17885962  7659.49493061
  1221.80482706  6851.60299355  1282.17885962  1282.17885962
  1282.17885962  1221.80482706  3919.50105408  7641.75179315
  1315.14566558  1277.12406128  1282.17885962  3403.94572716
  3322.91630156  4776.80069731  1277.12406128  3962.36249659
  1282.17885962  1221.80482706  8340.35272933  1221.80482706
 13959.45515267 10944.32814011  4752.08680776  1282.17885962
  1282.17885962 11201.25020848  1231.41896097  4776.31729731
  9090.16968389  1282.17885962  3387.62011404  3606.85618904
  8657.90364393  4540.44321496  3972.92726837  3405.66207255
  3462.69951022  4029.70367353  1282.17885962  1282.17885962
  6861.27586582  4778.02881094  4740.8507785   9100.97729581
 11192.24330577  1282.17885962  8494.08081858  3460.23873232
  1282.17885962  1282.17885962]

In [51]:
from sklearn.metrics import mean_absolute_error

y_pred = regressor.predict(X_validation)
print(mean_absolute_error(Y_validation, y_pred))

from sklearn.metrics import r2_score

#calculate R-squared of regression model
print("\tR2 score:", r2_score(Y_validation, y_pred))

881.7520032514534
	R2 score: 0.8940950088381391

Test

In [52]:
# test the output by changing values, like 3750
y_pred_test = regressor.predict(X_test)
  
# print the predicted price
print("Predicted Immatricolazioni:")
print(y_pred_test)

Predicted Immatricolazioni:
[ 1282.17885962 11185.69794951  5184.04689628  4593.17066878
  1277.12406128  1277.12406128  4263.94334903  6641.87053754
  1282.17885962  3460.23873232  1277.12406128 11283.61328049
  1282.17885962  6641.87053754  9571.72883843  4776.31729731
  6957.33042108  4861.45284728  8971.95100958  1282.17885962
 11334.62919045  4776.31729731  1282.17885962  4794.38603797
  1282.17885962  3458.67841963  1277.12406128  3614.40514869
  1288.63015312  4744.41010503  4706.40316127  4720.29819206
  1224.9703451   7727.7092967   8491.63581889  6843.87177673
  4715.35438408  1282.17885962  8964.67530877  4744.89350503
  4794.38603797  4511.99295202  4706.40316127  4776.31729731
  3634.40125669  9122.36742137  2857.50106891  1282.17885962
  1282.17885962  4744.89350503  1282.17885962  3460.23873232
  4776.31729731  4687.28226897  7634.84211581  5364.7284095
  1282.17885962  1282.17885962  3871.45915697  8811.14278155
  3686.48169012  6775.77704143  1282.17885962  6843.87177673
 11300.9950592   4699.91246672  1282.17885962  4776.31729731
  4419.54212014  4425.05642765  4251.03079608  1282.17885962
  8675.34514594  4216.77863871  6860.75476945  1821.17465239
  4740.02640234  1282.17885962  4776.80069731  8669.10290927
  1228.67552302  3403.94572716  3460.23873232  4776.31729731
  1282.17885962  3380.10371789  4778.02881094  8822.23908904
  4706.40316127 11321.34098843  1282.17885962  4776.31729731
  3204.40977231  8986.43290388  8963.64448665  4847.02281662
  9517.05178964  1226.85962541  1231.41896097  3606.85618904
  4776.31729731  6837.18289486  4776.31729731  1282.17885962
  4776.31729731  3462.11721463  1226.85962541  1221.80482706
  1221.80482706  1282.17885962  6870.42764171  3462.69951022
  1282.17885962  4794.38603797  3976.63221376  1282.17885962
  4629.91386092  4778.02881094 14023.40403474  3984.50391265
  3405.66207255 15294.82139486  1282.17885962  3974.64361376
  6641.87053754  4853.21900822  1277.12406128  4744.41010503
  1282.17885962  4776.31729731  1240.41541103  7622.90716103
  3460.23873232  1282.17885962  3395.09768615  3460.23873232
  1221.80482706  4744.41010503  8973.85825243  3403.94572716
 10964.87601334  8915.0268752   3460.23873232  3760.19603317
  4851.50034155  1282.17885962  4706.40316127  3462.69951022
  3460.23873232  1282.17885962  7023.98797631  1226.85962541
  8667.82548892  1277.12406128  9517.05178964  1224.9703451
  4776.31729731  1282.17885962  3443.58144752  9433.4122567
  1282.17885962  1282.17885962  3760.19603317]

In [53]:
from sklearn.metrics import mean_absolute_error

y_pred_test = regressor.predict(X_test)
print(mean_absolute_error(Y_test, y_pred_test))

from sklearn.metrics import r2_score

#calculate R-squared of regression model
print("\tR2 score:", r2_score(Y_test, y_pred_test))

1063.1555958604729
	R2 score: 0.8415456283413723

#Extratrees Regressor

In [20]:
import time

start = time.time()

from sklearn.ensemble import ExtraTreesRegressor
regressor = ExtraTreesRegressor(n_estimators=400,random_state=0)

regressor.fit(X_train,Y_train)

end = time.time()
print(format(end-start))

1.9493558406829834

In [21]:
# test the output by changing values, like 3750
y_pred = regressor.predict(X_validation)
  
# print the predicted price
print("Predicted Immatricolazioni:")
print(y_pred)

Predicted Immatricolazioni:
[ 4918.0225  1589.0475  9065.265    222.0075  1015.1     3753.31
  8491.8225  1917.935   2807.81    5398.24    3657.08   10909.7675
  2245.11   12806.9225  4905.3175  1840.03    3889.3825  1105.465
  6727.965   6939.19    4378.7675  1335.8825  1719.8125   830.9575
  4216.33     258.4575  3413.8975  2341.385   3586.1825  1536.15
  4787.1275  7154.295   1736.2975  5808.4175  1521.1925  1255.535
   661.0725   848.02   13975.0175 13683.0725  2545.9625  1006.2025
   844.8775  1712.62    1913.4225  1363.3675   402.3525 10154.7775
  3680.6275  1689.9325  2206.2125  3685.005   2973.815   1684.76
   658.3     2137.1875  1061.03   14798.2625  3643.6575   857.2925
  4129.18     853.78    3278.0425  2363.66    5862.4925  5928.4325
 15853.1025  4045.855   4020.335    806.53    1015.12    6432.675
   300.6425  5110.5475  2590.15    2832.27    2514.515    354.3975
  3445.41    7047.66    2076.825    843.1     1402.6675  2992.665
  1701.3225  5713.5      522.9175  3569.12    1392.225    204.405
  5355.67     292.23   15501.2975 10866.595   4890.03    1949.6225
   727.5    10531.8525   934.3875  2844.54   13206.6875  2534.0675
  2215.235   2891.735   6807.505   5294.6975  4146.425   2462.38
  4210.715   4177.4625  1616.4775  1052.2075  5140.7475  5995.02
  5899.465  10773.875  10302.5225  1253.0925  5609.8825  2715.325
  2537.1225   769.3175]

In [22]:
from sklearn.metrics import mean_absolute_error

y_pred = regressor.predict(X_validation)
print(mean_absolute_error(Y_validation, y_pred))

131.5344262295082

In [23]:
from sklearn.metrics import r2_score

#calculate R-squared of regression model
print("\tR2 score:", r2_score(Y_validation, y_pred))

	R2 score: 0.9965142061729695

Test

In [24]:
# test the output by changing values, like 3750
y_pred_test = regressor.predict(X_test)
  
# print the predicted price
print("Predicted Immatricolazioni:")
print(y_pred_test)

Predicted Immatricolazioni:
[ 1995.855  10102.3175  5121.1225  3764.3625   706.625   1594.2175
  4624.825   5166.29    2064.6825  3832.915    725.4925 11022.34
  1604.5525  5274.81   12492.9175  2742.54    4798.24    7929.275
  8077.125   1761.68   14342.8175  2804.1625  1811.885   6878.9875
  2424.26    2532.0175  1019.45    2983.5775  1469.935   3891.0625
  3707.7925  4879.4225   330.39    7169.32    5578.175   5052.31
  5980.885   2605.485   8562.7075  4510.2225  7009.655   5779.3225
  4908.605   2791.655   2997.5975 10688.3475  1744.43    1920.2425
  2169.99    4440.2475  1907.345   3347.95    4537.7     3349.1625
  6993.9525  4998.5425  2713.595   2776.7375  1610.9975  8083.955
  3275.04    7212.24     708.1975  4933.65   12756.3275  3701.0525
  2538.245   3187.195   4521.01    5442.2875  4435.7025  1897.8525
  7673.675   3798.9775  7260.1175  1732.475   6020.9525  2052.93
  3145.72    7227.865    225.955   2156.4725  2938.1525  2800.8075
  1859.0125  1800.49    5986.205   7844.955   5306.4475 13905.52
  1038.8375  2884.735   1651.9175  8613.4675  7614.9725  4011.5375
 12510.7475   179.8475   916.1475  3654.305   3277.765   4990.375
  5124.765   2724.3525  5311.315   3635.7725   188.7475   292.9625
   280.75    1888.255   7417.75    3870.105   1610.1125  6675.07
  3541.09    1599.9     3547.2775  5989.4425 16188.36    4198.125
  2924.3925 16024.365   2214.56    4044.4025  5279.4225  4702.0725
   770.615   4139.41     851.055   2786.01     994.4975  6703.135
  3486.7775  1898.18    2042.8825  2758.01     204.0175  4188.38
  8735.1725  2378.25   11906.695   7786.4175  3728.7425  4066.08
  4709.0725  2390.495   4928.0225  3674.5875  2661.46    1068.1775
  7761.68     183.8325  6193.365   1036.4025 12279.905    285.8975
  2758.83    2532.96    2835.9275 12055.67    2595.2725  1017.3325
  4146.065 ]

In [25]:
from sklearn.metrics import mean_absolute_error

y_pred_test = regressor.predict(X_test)
print(mean_absolute_error(Y_test, y_pred_test))

180.78190184049078

In [26]:
from sklearn.metrics import r2_score

#calculate R-squared of regression model
print("\tR2 score:", r2_score(Y_test, y_pred_test))

	R2 score: 0.9913159292736227

#Dataset Unito

In [27]:
X=df.drop(columns=['Immatricolati'])
Y=df["Immatricolati"]

In [28]:
#Split the training e validation 75% and 25% testing
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.30, random_state=0)

In [29]:
#Scale the data (Feature Scaling Z Score) z = (x - u) / s
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,

In [30]:
X_train = np.array(X_train)
X_test = np.array(X_test)

Y_train = np.array(Y_train)
Y_test = np.array(Y_test)

In [31]:
import time
start = time.time()

from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators=1000,max_depth=3, random_state=0) 

regressor.fit(X_train,Y_train)

end = time.time()
print(format(end-start))

1.6583707332611084

In [32]:
import time
start = time.time()

from sklearn.ensemble import ExtraTreesRegressor
regressor = ExtraTreesRegressor(n_estimators=400,random_state=0)

regressor.fit(X_train,Y_train)

end = time.time()
print(format(end-start))

2.010667085647583

In [33]:
# test the output by changing values, like 3750
y_pred_test = regressor.predict(X_test)
  
# print the predicted price
print("Predicted Immatricolazioni:")
print(y_pred_test)

Predicted Immatricolazioni:
[ 1888.9975 10115.19    5079.6625  3724.1      718.53    1593.115
  4636.1875  5093.01    1979.895   3835.32     724.1575 11079.4425
  1590.3675  5276.1725 12467.      2696.285   4740.9     7934.1975
  7959.31    1766.225  14261.1825  2697.4625  1916.3625  6872.77
  2441.1375  2522.48     988.4875  2882.6875  1417.0975  4290.5325
  3675.56    4789.5925   318.075   7120.525   5637.305   5111.0425
  5959.6825  2503.5725  8505.9425  4478.18    6997.1725  5791.515
  4916.68    2655.88    2889.47   10825.195   1453.3825  1915.5525
  2174.395   4392.655   1844.8625  3240.3475  4038.21    3460.7575
  6949.775   5163.1525  2715.6075  2775.925   1542.385   8025.81
  3264.03    7220.6875   675.8425  4932.76   12738.3525  3659.3525
  2463.4825  3124.955   4452.2925  5447.965   4736.03    1910.17
  7636.9775  3785.8875  7277.615   1400.74    5834.715   1977.455
  2978.1725  7227.1      258.6175  2193.74    2932.0575  2851.2025
  1968.3325  1790.5075  5994.4825  7790.6     5292.7775 13444.845
  1164.155   2915.875   1655.825   8248.97    7699.925   4051.705
 12459.9475   179.63     932.8125  3673.04    3278.315   5034.9375
  5154.2625  2736.91    5333.5275  3740.565    188.695    278.6975
   280.0275  1873.1525  7403.7725  3989.18    1659.285   6639.935
  3562.745   1562.9325  3557.3175  5994.8325 16415.575   3944.5975
  2934.9625 16004.765   2199.4     4042.515   5241.8375  4805.01
   771.9375  4187.465    836.5975  2669.9425  1001.2175  6688.86
  3431.715   2016.5275  2035.16    2698.195    203.32    4195.59
  8742.6475  2328.43   11888.7975  7793.93    3761.76    4064.43
  4848.4175  2451.02    4937.7375  3798.2725  2668.5475   999.3875
  7698.1625   184.0825  6233.7525  1235.3475 12294.5975   279.9575
  2697.735   2552.665   2834.605  12053.2525  2739.2275  1007.8275
  4142.515  10851.7175   363.12    1675.365   1768.5325   273.9025
  5937.2025  1680.5275   204.625    318.4825 13524.5075   977.6525
  3523.9     7133.79    2945.955   4388.15    4893.3875 11394.9375
  4098.7725  2247.24    1424.39    1911.6225  5413.6075  4304.2375
  6664.2325  1965.7175  3974.32    4322.3875   726.2975  1211.025
   601.375   3950.555   2079.785 ]

In [34]:
from sklearn.metrics import mean_absolute_error

y_pred_test = regressor.predict(X_test)
print(mean_absolute_error(Y_test, y_pred_test))

156.63657692307692

In [35]:
from sklearn.metrics import r2_score

#calculate R-squared of regression model
print("\tR2 score:", r2_score(Y_test, y_pred_test))

	R2 score: 0.9929895833630742

#TRAINING FINALE

In [ ]:
X=df.drop(columns=['Immatricolati'])
Y=df["Immatricolati"]

In [ ]:
#Scale the data (Feature Scaling Z Score) z = (x - u) / s
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X = sc.fit_transform(X)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,

In [ ]:
X = np.array(X)
Y = np.array(Y)

In [ ]:
from sklearn.ensemble import ExtraTreesRegressor
regressor = ExtraTreesRegressor(n_estimators=400,random_state=0)

regressor.fit(X,Y)

ExtraTreesRegressor(n_estimators=400, random_state=0)

#Testing

In [ ]:
with open("/content/drive/MyDrive/KPMG/RegressionDatasetTest_finale.xlsx", 'rb') as fp:
    df = pd.read_excel(fp)

In [ ]:
df

,AnnoAccademico,Ateneo,PopolazioneP,AteneiP,PopolazioneR,AteneiR,FuoriSede,Immatricolati
0,2021/2022,Aosta,123041,1,123704,1,77,246
1,2022/2023,Aosta,122745,1,123408,1,81,248
2,2023/2024,Aosta,122449,1,123112,1,85,250
3,2024/2025,Aosta,122153,1,122816,1,89,252
4,2025/2026,Aosta,121857,1,122520,1,93,254
...,...,...,...,...,...,...,...,...
290,2021/2022,Verona,929582,1,4870663,4,2545,4695
291,2022/2023,Verona,932056,1,4871326,4,2543,4672
292,2023/2024,Verona,934530,1,4871989,4,2541,4649
293,2024/2025,Verona,937004,1,4872652,4,2539,4626
294,2025/2026,Verona,939478,1,4873315,4,2537,4603

In [ ]:
df1=df

In [ ]:
categorical_cols=df.columns[df.dtypes==object].tolist()
categorical_cols

['AnnoAccademico', 'Ateneo']

In [ ]:
from sklearn.preprocessing import OneHotEncoder

#creating instance of one-hot-encoder
encoder = OneHotEncoder(handle_unknown='ignore')

#perform one-hot encoding on 'team' column 
encoder_df = pd.DataFrame(encoder.fit_transform(df[['Ateneo']]).toarray())

#merge one-hot encoded columns back with original DataFrame
final_df = df.join(encoder_df)

#view final df
print(final_df)

    AnnoAccademico  Ateneo  PopolazioneP  AteneiP  PopolazioneR  AteneiR  \
0        2021/2022   Aosta        123041        1        123704        1
1        2022/2023   Aosta        122745        1        123408        1
2        2023/2024   Aosta        122449        1        123112        1
3        2024/2025   Aosta        122153        1        122816        1
4        2025/2026   Aosta        121857        1        122520        1
..             ...     ...           ...      ...           ...      ...
290      2021/2022  Verona        929582        1       4870663        4
291      2022/2023  Verona        932056        1       4871326        4
292      2023/2024  Verona        934530        1       4871989        4
293      2024/2025  Verona        937004        1       4872652        4
294      2025/2026  Verona        939478        1       4873315        4

     FuoriSede  Immatricolati    0    1  ...   49   50   51   52   53   54  \
0           77            246  1.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
1           81            248  1.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
2           85            250  1.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
3           89            252  1.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
4           93            254  1.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
..         ...            ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
290       2545           4695  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
291       2543           4672  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
292       2541           4649  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
293       2539           4626  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
294       2537           4603  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0

      55   56   57   58
0    0.0  0.0  0.0  0.0
1    0.0  0.0  0.0  0.0
2    0.0  0.0  0.0  0.0
3    0.0  0.0  0.0  0.0
4    0.0  0.0  0.0  0.0
..   ...  ...  ...  ...
290  0.0  0.0  0.0  1.0
291  0.0  0.0  0.0  1.0
292  0.0  0.0  0.0  1.0
293  0.0  0.0  0.0  1.0
294  0.0  0.0  0.0  1.0

[295 rows x 67 columns]

In [ ]:
df=final_df

In [ ]:
df=df.drop(columns=['Ateneo'])

In [ ]:
df["AnnoAccademico"]=df["AnnoAccademico"].astype('category').cat.codes

In [ ]:
df

,AnnoAccademico,PopolazioneP,AteneiP,PopolazioneR,AteneiR,FuoriSede,Immatricolati,0,1,2,...,49,50,51,52,53,54,55,56,57,58
0,0,123041,1,123704,1,77,246,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,122745,1,123408,1,81,248,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,122449,1,123112,1,85,250,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,122153,1,122816,1,89,252,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,121857,1,122520,1,93,254,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
290,0,929582,1,4870663,4,2545,4695,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
291,1,932056,1,4871326,4,2543,4672,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
292,2,934530,1,4871989,4,2541,4649,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
293,3,937004,1,4872652,4,2539,4626,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
294,4,939478,1,4873315,4,2537,4603,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [ ]:
df = df.fillna(0)

In [ ]:
df = df.astype({'FuoriSede': int})

In [ ]:
X=df.drop(columns=['Immatricolati'])

In [ ]:
sc=StandardScaler()
X = sc.fit_transform(X)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,

In [ ]:
X = np.array(X)

In [ ]:
y_pred = regressor.predict(X)
  
# print the predicted price
print("Predicted Immatricolazioni:")
print(y_pred)

Predicted Immatricolazioni:
[  191.3875   188.4875   185.035    185.59     190.97    6831.05
  6714.9925  6520.7275  6429.825   6302.6125  1582.67    1591.405
  1624.1025  1704.585   1738.7125   911.0125   867.6225   861.14
   860.4675   867.39    2943.14    3067.885   3282.85    3451.305
  3579.805  12625.69   12645.76   12774.855  12876.59   13019.445
  2784.12    2863.8825  2971.84    3085.795   3194.5075  3797.52
  3790.6875  3831.02    3866.3025  3967.135   4062.375   4012.09
  3992.505   4002.8625  4020.76    6203.37    6205.9975  6237.41
  6212.1325  6221.2875  1444.7925  1467.045   1486.2575  1554.3
  1576.16    4035.6025  3811.605   3688.5675  3559.8775  3446.4875
   772.3425   819.94     769.25     779.56     966.6625  6442.12
  6894.8625  7425.7975  8028.3125  8674.4475  8352.12    8435.2725
  8637.045   8768.1275  8915.7075  2067.8375  2194.865   2338.0025
  2469.085   2497.115   6315.425   6359.545   6437.785   6544.8875
  6659.4075  1362.8775  1377.9975  1461.315   1528.49    1546.615
  2644.7675  2655.705   2655.115   2666.7175  2733.6825  4485.5175
  4381.3725  4334.6225  4377.9075  4453.37   10999.7775 10880.8025
 10837.45   10717.1675 10871.1875  4983.7025  4867.4975  4785.02
  4719.105   4726.28    2497.23    2516.6725  2558.875   2576.53
  2647.56    6867.7825  6971.8975  7090.395   7209.1825  7407.5025
  1306.18    1366.2625  1459.6475  1649.5375  1958.6775  6832.14
  6934.65    7071.285   7175.6375  7312.22     271.5775   277.0375
   298.7425   307.9475   381.25    4894.7375  4940.4625  5137.0525
  5298.6     5499.7275  1036.675    975.4675   972.95     986.8375
  1007.0425  1276.2825  1264.6975  1254.9175  1272.4075  1299.1625
 13756.4425 13676.9675 13706.81   13812.585  13993.795   1822.71
  1950.395   1993.9025  2030.2375  2049.2675  2093.4575  1988.4475
  1816.22    1633.815   1580.225   3367.5125  3367.125   3395.495
  3478.48    3535.5975 10576.8075 10752.7775 10941.5075 11085.285
 11431.995   7496.3725  7497.03    7518.45    7552.4425  7743.095
  4853.71    4888.1025  4909.77    4987.7975  5069.5625  4029.8975
  4083.69    4187.4425  4299.99    4407.045   5186.86    5315.8975
  5439.13    5641.4575  5927.8925  6411.195   6403.9275  6448.5325
  6473.535   6523.4      217.405    227.09     253.9325   260.6125
   326.775    274.8125   274.4125   286.1225   290.0225   334.1125
 14971.6675 15055.45   15643.6075 16472.88   16839.2275  1315.89
  1349.3325  1448.38    1509.4575  1566.8275   632.9525   614.065
   592.2625   614.86     714.81    4822.0075  4757.      4695.525
  4643.24    4613.2825  5694.9025  5662.41    5619.6     5603.88
  5589.17    5359.6325  5385.38    5497.905   5600.4925  5678.01
  1853.0175  1838.41    1850.8875  1964.72    2026.61    1937.9625
  1915.235   1891.8325  1882.06    1850.585    814.6775   811.1775
   820.6125   833.8525   911.54   13071.2725 13339.3125 13684.4525
 14080.7825 14394.2625  4747.2775  4896.1575  4965.025   4994.3275
  5040.8675  2878.655   2864.49    2870.5475  2886.27    2961.0575
  2462.765   2457.8575  2435.9975  2442.43    2470.1225  2767.5275
  2799.895   2844.03    2862.9525  2900.7575  3248.985   3293.1625
  3350.0475  3436.83    3537.48     933.7025   936.985    901.085
   919.4125  1397.1775  4099.4725  4061.125   4015.5325  3942.525
  3920.5875]

In [ ]:
len(y_pred)

295

In [ ]:
df1 = df1.assign(ImmatricolazioniPredette=y_pred)

In [ ]:
df1

,AnnoAccademico,Ateneo,PopolazioneP,AteneiP,PopolazioneR,AteneiR,FuoriSede,Immatricolati,ImmatricolazioniPredette
0,2021/2022,Aosta,123041,1,123704,1,77,246,191.3875
1,2022/2023,Aosta,122745,1,123408,1,81,248,188.4875
2,2023/2024,Aosta,122449,1,123112,1,85,250,185.0350
3,2024/2025,Aosta,122153,1,122816,1,89,252,185.5900
4,2025/2026,Aosta,121857,1,122520,1,93,254,190.9700
...,...,...,...,...,...,...,...,...,...
290,2021/2022,Verona,929582,1,4870663,4,2545,4695,4099.4725
291,2022/2023,Verona,932056,1,4871326,4,2543,4672,4061.1250
292,2023/2024,Verona,934530,1,4871989,4,2541,4649,4015.5325
293,2024/2025,Verona,937004,1,4872652,4,2539,4626,3942.5250
294,2025/2026,Verona,939478,1,4873315,4,2537,4603,3920.5875

In [ ]:
df1.drop(columns='Immatricolati')

,AnnoAccademico,Ateneo,PopolazioneP,AteneiP,PopolazioneR,AteneiR,FuoriSede,ImmatricolazioniPredette
0,2021/2022,Aosta,123041,1,123704,1,77,191.3875
1,2022/2023,Aosta,122745,1,123408,1,81,188.4875
2,2023/2024,Aosta,122449,1,123112,1,85,185.0350
3,2024/2025,Aosta,122153,1,122816,1,89,185.5900
4,2025/2026,Aosta,121857,1,122520,1,93,190.9700
...,...,...,...,...,...,...,...,...
290,2021/2022,Verona,929582,1,4870663,4,2545,4099.4725
291,2022/2023,Verona,932056,1,4871326,4,2543,4061.1250
292,2023/2024,Verona,934530,1,4871989,4,2541,4015.5325
293,2024/2025,Verona,937004,1,4872652,4,2539,3942.5250
294,2025/2026,Verona,939478,1,4873315,4,2537,3920.5875

In [ ]:
df1.to_excel("/content/drive/MyDrive/KPMG/Risultato_regressione_finale.xlsx", sheet_name="Risultati", index=False)