In [ ]:
#importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()

In [ ]:
#Collegamento al Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

#Sklearn

In [ ]:
with open("/content/drive/MyDrive/KPMG/RegressionDataset.xlsx", 'rb') as fp:
    df = pd.read_excel(fp)

In [ ]:
df

,AnnoAccademico,Ateneo,PopolazioneP,AteneiP,PopolazioneR,AteneiR,Fuorisede,Immatricolati
0,2010/2011,Aosta,126957,1,126957,1,31,188
1,2011/2012,Aosta,127153,1,127153,1,21,172
2,2012/2013,Aosta,127305,1,127305,1,31,173
3,2013/2014,Aosta,127951,1,127951,1,54,192
4,2014/2015,Aosta,128245,1,128245,1,52,181
...,...,...,...,...,...,...,...,...
644,2016/2017,Verona,918050,1,4890648,4,2509,4553
645,2017/2018,Verona,918069,1,4883373,4,2477,4484
646,2018/2019,Verona,919179,1,4880936,4,2098,3874
647,2019/2020,Verona,922857,1,4884590,4,2082,3785
648,2020/2021,Verona,927108,1,4870000,4,2547,4718

In [ ]:
df1=df

In [ ]:
categorical_cols=df.columns[df.dtypes==object].tolist()
categorical_cols

['AnnoAccademico', 'Ateneo']

In [ ]:
from sklearn.preprocessing import OneHotEncoder

#creating instance of one-hot-encoder
encoder = OneHotEncoder(handle_unknown='ignore')

#perform one-hot encoding on 'team' column 
encoder_df = pd.DataFrame(encoder.fit_transform(df[['Ateneo']]).toarray())

#merge one-hot encoded columns back with original DataFrame
final_df = df.join(encoder_df)

#view final df
print(final_df)

    AnnoAccademico  Ateneo  PopolazioneP  AteneiP  PopolazioneR  AteneiR  \
0        2010/2011   Aosta        126957        1        126957        1
1        2011/2012   Aosta        127153        1        127153        1
2        2012/2013   Aosta        127305        1        127305        1
3        2013/2014   Aosta        127951        1        127951        1
4        2014/2015   Aosta        128245        1        128245        1
..             ...     ...           ...      ...           ...      ...
644      2016/2017  Verona        918050        1       4890648        4
645      2017/2018  Verona        918069        1       4883373        4
646      2018/2019  Verona        919179        1       4880936        4
647      2019/2020  Verona        922857        1       4884590        4
648      2020/2021  Verona        927108        1       4870000        4

     Fuorisede  Immatricolati    0    1  ...   49   50   51   52   53   54  \
0           31            188  1.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
1           21            172  1.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
2           31            173  1.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
3           54            192  1.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
4           52            181  1.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
..         ...            ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
644       2509           4553  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
645       2477           4484  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
646       2098           3874  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
647       2082           3785  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
648       2547           4718  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0

      55   56   57   58
0    0.0  0.0  0.0  0.0
1    0.0  0.0  0.0  0.0
2    0.0  0.0  0.0  0.0
3    0.0  0.0  0.0  0.0
4    0.0  0.0  0.0  0.0
..   ...  ...  ...  ...
644  0.0  0.0  0.0  1.0
645  0.0  0.0  0.0  1.0
646  0.0  0.0  0.0  1.0
647  0.0  0.0  0.0  1.0
648  0.0  0.0  0.0  1.0

[649 rows x 67 columns]

In [ ]:
df=final_df

In [ ]:
df["AnnoAccademico"]=df["AnnoAccademico"].astype('category').cat.codes
#df["AteneoNOME"]=df["AteneoNOME"].astype('category').cat.codes

In [ ]:
df=df.drop(columns=['Ateneo'])

In [ ]:
df

,AnnoAccademico,PopolazioneP,AteneiP,PopolazioneR,AteneiR,Fuorisede,Immatricolati,0,1,2,...,49,50,51,52,53,54,55,56,57,58
0,0,126957,1,126957,1,31,188,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,127153,1,127153,1,21,172,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,127305,1,127305,1,31,173,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,127951,1,127951,1,54,192,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,128245,1,128245,1,52,181,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,6,918050,1,4890648,4,2509,4553,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
645,7,918069,1,4883373,4,2477,4484,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
646,8,919179,1,4880936,4,2098,3874,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
647,9,922857,1,4884590,4,2082,3785,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
648,11,927108,1,4870000,4,2547,4718,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [ ]:
df = df.fillna(0)

In [ ]:
df = df.astype({'Fuorisede': int})

In [ ]:
df.columns

Index(['AnnoAccademico',   'PopolazioneP',        'AteneiP',   'PopolazioneR',
              'AteneiR',      'Fuorisede',  'Immatricolati',                0,
                      1,                2,                3,                4,
                      5,                6,                7,                8,
                      9,               10,               11,               12,
                     13,               14,               15,               16,
                     17,               18,               19,               20,
                     21,               22,               23,               24,
                     25,               26,               27,               28,
                     29,               30,               31,               32,
                     33,               34,               35,               36,
                     37,               38,               39,               40,
                     41,               42,               43,               44,
                     45,               46,               47,               48,
                     49,               50,               51,               52,
                     53,               54,               55,               56,
                     57,               58],
      dtype='object')

In [ ]:
X=df.drop(columns=['Immatricolati'])
Y=df["Immatricolati"]

In [ ]:
#Split the training e validation 75% and 25% testing
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, random_state=0)

In [ ]:
#Split the training e validation 75% and 25% testing
from sklearn.model_selection import train_test_split

X_train, X_validation, Y_train, Y_validation = train_test_split(X_train, Y_train, test_size=0.25, random_state=0)

In [ ]:
#Scale the data (Feature Scaling Z Score) z = (x - u) / s
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train = sc.fit_transform(X_train)
X_validation=sc.transform(X_validation)
X_test = sc.transform(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,

In [ ]:
X_train = np.array(X_train)
X_validation=np.array(X_validation)
X_test = np.array(X_test)

Y_train = np.array(Y_train)
Y_validation=np.array(Y_validation)
Y_test = np.array(Y_test)

In [ ]:
#criterion{“squared_error”, “absolute_error”}, default=”squared_error”
from sklearn.ensemble import GradientBoostingRegressor

regressor = GradientBoostingRegressor(criterion= 'squared_error', learning_rate= 1, loss= 'squared_error', max_features= 'log2') 

regressor.fit(X_train,Y_train)

GradientBoostingRegressor(criterion='squared_error', learning_rate=1,
                          max_features='log2')

In [ ]:
from sklearn.ensemble import ExtraTreesRegressor
regressor = ExtraTreesRegressor(n_estimators=400,random_state=0)

regressor.fit(X_train,Y_train)

ExtraTreesRegressor(n_estimators=400, random_state=0)

In [ ]:
# test the output by changing values, like 3750
y_pred = regressor.predict(X_validation)
  
# print the predicted price
print("Predicted Immatricolazioni:")
print(y_pred)

Predicted Immatricolazioni:
[ 4918.0225  1589.0475  9065.265    222.0075  1015.1     3753.31
  8491.8225  1917.935   2807.81    5398.24    3657.08   10909.7675
  2245.11   12806.9225  4905.3175  1840.03    3889.3825  1105.465
  6727.965   6939.19    4378.7675  1335.8825  1719.8125   830.9575
  4216.33     258.4575  3413.8975  2341.385   3586.1825  1536.15
  4787.1275  7154.295   1736.2975  5808.4175  1521.1925  1255.535
   661.0725   848.02   13975.0175 13683.0725  2545.9625  1006.2025
   844.8775  1712.62    1913.4225  1363.3675   402.3525 10154.7775
  3680.6275  1689.9325  2206.2125  3685.005   2973.815   1684.76
   658.3     2137.1875  1061.03   14798.2625  3643.6575   857.2925
  4129.18     853.78    3278.0425  2363.66    5862.4925  5928.4325
 15853.1025  4045.855   4020.335    806.53    1015.12    6432.675
   300.6425  5110.5475  2590.15    2832.27    2514.515    354.3975
  3445.41    7047.66    2076.825    843.1     1402.6675  2992.665
  1701.3225  5713.5      522.9175  3569.12    1392.225    204.405
  5355.67     292.23   15501.2975 10866.595   4890.03    1949.6225
   727.5    10531.8525   934.3875  2844.54   13206.6875  2534.0675
  2215.235   2891.735   6807.505   5294.6975  4146.425   2462.38
  4210.715   4177.4625  1616.4775  1052.2075  5140.7475  5995.02
  5899.465  10773.875  10302.5225  1253.0925  5609.8825  2715.325
  2537.1225   769.3175]

In [ ]:
from sklearn.metrics import mean_absolute_error

y_pred = regressor.predict(X_validation)
print(mean_absolute_error(Y_validation, y_pred))
#get_depth returns the depth of the tree

131.5344262295082

In [ ]:
from sklearn.metrics import r2_score

#calculate R-squared of regression model
print("\tR2 score:", r2_score(Y_validation, y_pred))

	R2 score: 0.9965142061729695

Test

In [ ]:
# test the output by changing values, like 3750
y_pred_test = regressor.predict(X_test)
  
# print the predicted price
print("Predicted Immatricolazioni:")
print(y_pred_test)

Predicted Immatricolazioni:
[ 1995.855  10102.3175  5121.1225  3764.3625   706.625   1594.2175
  4624.825   5166.29    2064.6825  3832.915    725.4925 11022.34
  1604.5525  5274.81   12492.9175  2742.54    4798.24    7929.275
  8077.125   1761.68   14342.8175  2804.1625  1811.885   6878.9875
  2424.26    2532.0175  1019.45    2983.5775  1469.935   3891.0625
  3707.7925  4879.4225   330.39    7169.32    5578.175   5052.31
  5980.885   2605.485   8562.7075  4510.2225  7009.655   5779.3225
  4908.605   2791.655   2997.5975 10688.3475  1744.43    1920.2425
  2169.99    4440.2475  1907.345   3347.95    4537.7     3349.1625
  6993.9525  4998.5425  2713.595   2776.7375  1610.9975  8083.955
  3275.04    7212.24     708.1975  4933.65   12756.3275  3701.0525
  2538.245   3187.195   4521.01    5442.2875  4435.7025  1897.8525
  7673.675   3798.9775  7260.1175  1732.475   6020.9525  2052.93
  3145.72    7227.865    225.955   2156.4725  2938.1525  2800.8075
  1859.0125  1800.49    5986.205   7844.955   5306.4475 13905.52
  1038.8375  2884.735   1651.9175  8613.4675  7614.9725  4011.5375
 12510.7475   179.8475   916.1475  3654.305   3277.765   4990.375
  5124.765   2724.3525  5311.315   3635.7725   188.7475   292.9625
   280.75    1888.255   7417.75    3870.105   1610.1125  6675.07
  3541.09    1599.9     3547.2775  5989.4425 16188.36    4198.125
  2924.3925 16024.365   2214.56    4044.4025  5279.4225  4702.0725
   770.615   4139.41     851.055   2786.01     994.4975  6703.135
  3486.7775  1898.18    2042.8825  2758.01     204.0175  4188.38
  8735.1725  2378.25   11906.695   7786.4175  3728.7425  4066.08
  4709.0725  2390.495   4928.0225  3674.5875  2661.46    1068.1775
  7761.68     183.8325  6193.365   1036.4025 12279.905    285.8975
  2758.83    2532.96    2835.9275 12055.67    2595.2725  1017.3325
  4146.065 ]

In [ ]:
from sklearn.metrics import mean_absolute_error

y_pred_test = regressor.predict(X_test)
print(mean_absolute_error(Y_test, y_pred_test))

180.78190184049078

In [ ]:
from sklearn.metrics import r2_score

#calculate R-squared of regression model
print("\tR2 score:", r2_score(Y_test, y_pred_test))

	R2 score: 0.9913159292736227

#Dataset Unito

In [ ]:
X=df.drop(columns=['Immatricolati'])
Y=df["Immatricolati"]

In [ ]:
#Split the training e validation 75% and 25% testing
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.30, random_state=0)

In [ ]:
#Scale the data (Feature Scaling Z Score) z = (x - u) / s
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,

In [ ]:
X_train = np.array(X_train)
X_test = np.array(X_test)

Y_train = np.array(Y_train)
Y_test = np.array(Y_test)

In [ ]:
from sklearn.ensemble import ExtraTreesRegressor
regressor = ExtraTreesRegressor(n_estimators=400,random_state=0)

regressor.fit(X_train,Y_train)

ExtraTreesRegressor(n_estimators=500, random_state=0)

In [ ]:
# test the output by changing values, like 3750
y_pred_test = regressor.predict(X_test)
  
# print the predicted price
print("Predicted Immatricolazioni:")
print(y_pred_test)

Predicted Immatricolazioni:
[ 1892.14  10110.864  5078.216  3717.938   723.348  1593.246  4626.012
  5090.232  1979.112  3841.142   728.776 11068.58   1590.274  5279.708
 12461.496  2701.19   4754.312  7925.08   7969.734  1768.674 14268.746
  2696.138  1916.902  6861.608  2445.268  2523.262   981.87   2880.854
  1417.244  4270.862  3672.096  4783.852   323.226  7128.114  5632.67
  5116.102  5965.492  2497.628  8505.028  4480.852  6988.226  5786.456
  4910.74   2655.362  2886.632 10823.524  1452.044  1921.276  2175.012
  4395.398  1847.162  3260.53   4040.036  3452.102  6953.256  5153.63
  2711.234  2773.932  1544.344  8026.092  3263.124  7218.78    673.726
  4927.464 12745.452  3655.116  2464.16   3099.112  4458.34   5449.162
  4734.678  1913.848  7639.356  3787.52   7278.514  1403.33   5857.898
  1981.338  2948.546  7226.824   259.21   2196.65   2920.808  2836.904
  1967.24   1790.142  5991.024  7794.702  5293.934 13440.516  1149.156
  2896.26   1655.916  8264.234  7705.242  4055.292 12455.89    179.984
   932.83   3673.346  3278.536  5029.78   5155.464  2734.48   5331.32
  3746.448   188.516   279.584   279.808  1881.234  7412.414  3992.672
  1666.298  6628.294  3563.466  1560.384  3556.72   5991.776 16405.452
  3954.058  2933.332 16011.376  2199.166  4032.07   5239.     4806.258
   769.43   4188.506   836.846  2676.94    999.986  6690.262  3433.616
  2018.622  2036.38   2700.682   203.194  4196.184  8739.656  2323.9
 11899.678  7816.804  3763.85   4064.562  4853.48   2443.138  4935.246
  3806.232  2664.434   999.93   7688.3     184.     6221.518  1230.81
 12272.816   282.022  2702.468  2548.67   2834.116 12054.314  2740.256
  1006.338  4143.296 10846.806   362.67   1674.37   1769.708   273.912
  5937.494  1684.396   204.408   320.952 13525.972   975.346  3523.998
  7127.136  2945.04   4390.42   4883.956 11365.244  4125.428  2248.656
  1439.858  1911.018  5414.662  4314.832  6661.736  1964.974  3976.26
  4300.918   729.734  1220.584   603.286  3952.204  2078.426]

In [ ]:
from sklearn.metrics import mean_absolute_error

y_pred_test = regressor.predict(X_test)
print(mean_absolute_error(Y_test, y_pred_test))

156.19932307692306

In [ ]:
from sklearn.metrics import r2_score

#calculate R-squared of regression model
print("\tR2 score:", r2_score(Y_test, y_pred_test))

	R2 score: 0.9929998860503189

#TRAINING FINALE

In [ ]:
X=df.drop(columns=['Immatricolati'])
Y=df["Immatricolati"]

In [ ]:
#Scale the data (Feature Scaling Z Score) z = (x - u) / s
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X = sc.fit_transform(X)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,

In [ ]:
X = np.array(X)
Y = np.array(Y)

In [ ]:
from sklearn.ensemble import ExtraTreesRegressor
regressor = ExtraTreesRegressor(n_estimators=400,random_state=0)

regressor.fit(X,Y)

ExtraTreesRegressor(n_estimators=500, random_state=0)

#Testing

In [ ]:
with open("/content/drive/MyDrive/KPMG/RegressionDatasetTest_finale.xlsx", 'rb') as fp:
    df = pd.read_excel(fp)

In [ ]:
df

,AnnoAccademico,Ateneo,PopolazioneP,AteneiP,PopolazioneR,AteneiR,FuoriSede,Immatricolati
0,2021/2022,Aosta,123041,1,123704,1,77,246
1,2022/2023,Aosta,122745,1,123408,1,81,248
2,2023/2024,Aosta,122449,1,123112,1,85,250
3,2024/2025,Aosta,122153,1,122816,1,89,252
4,2025/2026,Aosta,121857,1,122520,1,93,254
...,...,...,...,...,...,...,...,...
290,2021/2022,Verona,929582,1,4870663,4,2545,4695
291,2022/2023,Verona,932056,1,4871326,4,2543,4672
292,2023/2024,Verona,934530,1,4871989,4,2541,4649
293,2024/2025,Verona,937004,1,4872652,4,2539,4626
294,2025/2026,Verona,939478,1,4873315,4,2537,4603

In [ ]:
df1=df

In [ ]:
categorical_cols=df.columns[df.dtypes==object].tolist()
categorical_cols

['AnnoAccademico', 'Ateneo']

In [ ]:
from sklearn.preprocessing import OneHotEncoder

#creating instance of one-hot-encoder
encoder = OneHotEncoder(handle_unknown='ignore')

#perform one-hot encoding on 'team' column 
encoder_df = pd.DataFrame(encoder.fit_transform(df[['Ateneo']]).toarray())

#merge one-hot encoded columns back with original DataFrame
final_df = df.join(encoder_df)

#view final df
print(final_df)

    AnnoAccademico  Ateneo  PopolazioneP  AteneiP  PopolazioneR  AteneiR  \
0        2021/2022   Aosta        123041        1        123704        1
1        2022/2023   Aosta        122745        1        123408        1
2        2023/2024   Aosta        122449        1        123112        1
3        2024/2025   Aosta        122153        1        122816        1
4        2025/2026   Aosta        121857        1        122520        1
..             ...     ...           ...      ...           ...      ...
290      2021/2022  Verona        929582        1       4870663        4
291      2022/2023  Verona        932056        1       4871326        4
292      2023/2024  Verona        934530        1       4871989        4
293      2024/2025  Verona        937004        1       4872652        4
294      2025/2026  Verona        939478        1       4873315        4

     FuoriSede  Immatricolati    0    1  ...   49   50   51   52   53   54  \
0           77            246  1.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
1           81            248  1.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
2           85            250  1.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
3           89            252  1.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
4           93            254  1.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
..         ...            ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
290       2545           4695  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
291       2543           4672  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
292       2541           4649  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
293       2539           4626  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
294       2537           4603  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0

      55   56   57   58
0    0.0  0.0  0.0  0.0
1    0.0  0.0  0.0  0.0
2    0.0  0.0  0.0  0.0
3    0.0  0.0  0.0  0.0
4    0.0  0.0  0.0  0.0
..   ...  ...  ...  ...
290  0.0  0.0  0.0  1.0
291  0.0  0.0  0.0  1.0
292  0.0  0.0  0.0  1.0
293  0.0  0.0  0.0  1.0
294  0.0  0.0  0.0  1.0

[295 rows x 67 columns]

In [ ]:
df=final_df

In [ ]:
df=df.drop(columns=['Ateneo'])

In [ ]:
df["AnnoAccademico"]=df["AnnoAccademico"].astype('category').cat.codes

In [ ]:
df

,AnnoAccademico,PopolazioneP,AteneiP,PopolazioneR,AteneiR,FuoriSede,Immatricolati,0,1,2,...,49,50,51,52,53,54,55,56,57,58
0,0,123041,1,123704,1,77,246,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,122745,1,123408,1,81,248,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,122449,1,123112,1,85,250,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,122153,1,122816,1,89,252,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,121857,1,122520,1,93,254,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
290,0,929582,1,4870663,4,2545,4695,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
291,1,932056,1,4871326,4,2543,4672,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
292,2,934530,1,4871989,4,2541,4649,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
293,3,937004,1,4872652,4,2539,4626,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
294,4,939478,1,4873315,4,2537,4603,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [ ]:
df = df.fillna(0)

In [ ]:
df = df.astype({'FuoriSede': int})

In [ ]:
X=df.drop(columns=['Immatricolati'])

In [ ]:
sc=StandardScaler()
X = sc.fit_transform(X)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,

In [ ]:
X = np.array(X)

In [ ]:
y_pred = regressor.predict(X)
  
# print the predicted price
print("Predicted Immatricolazioni:")
print(y_pred)

Predicted Immatricolazioni:
[  191.412   188.846   185.276   185.746   191.522  6795.466  6664.226
  6476.222  6389.808  6276.206  1580.134  1586.258  1618.634  1701.3
  1727.402   915.806   872.768   862.966   861.75    869.324  2946.674
  3067.762  3283.562  3454.584  3573.328 12617.802 12646.716 12769.77
 12869.694 13003.062  2787.056  2864.698  2974.634  3089.766  3195.698
  3799.626  3793.26   3834.362  3868.05   3968.008  4062.81   4009.686
  3990.288  4002.132  4025.978  6204.664  6209.236  6239.962  6217.058
  6227.104  1445.35   1471.72   1487.224  1556.028  1580.88   4013.26
  3799.084  3678.218  3551.724  3442.988   774.042   811.832   764.572
   779.228   961.584  6452.108  6907.418  7443.068  8103.802  8669.276
  8360.16   8439.35   8629.59   8773.184  8927.652  2072.546  2196.496
  2331.844  2465.596  2489.518  6286.362  6323.008  6407.284  6529.294
  6660.01   1362.326  1377.13   1458.844  1531.896  1554.178  2642.86
  2653.292  2653.786  2664.476  2731.794  4491.704  4391.584  4344.326
  4380.876  4458.778 11006.822 10889.618 10848.396 10734.622 10879.454
  5012.016  4894.316  4808.684  4731.692  4744.674  2487.018  2508.386
  2552.836  2574.944  2638.296  6867.25   6971.172  7101.43   7208.374
  7399.566  1300.486  1364.996  1462.39   1648.868  1965.078  6833.856
  6935.316  7078.61   7177.868  7306.93    271.604   278.486   299.618
   310.732   382.142  4891.722  4930.058  5139.992  5301.246  5503.54
  1034.976   975.252   973.794   986.712  1005.86   1277.63   1265.724
  1256.726  1274.25   1300.456 13778.582 13709.438 13737.786 13831.47
 14005.032  1816.838  1945.942  1994.652  2029.098  2047.882  2086.958
  1983.686  1815.538  1641.526  1592.454  3369.312  3391.442  3420.006
  3498.316  3550.604 10569.756 10740.112 10942.498 11086.05  11418.758
  7495.64   7497.08   7518.772  7549.702  7724.272  4855.126  4894.518
  4916.222  4995.146  5081.21   4030.804  4085.246  4194.466  4296.344
  4414.906  5172.     5300.602  5425.938  5634.382  5935.85   6403.35
  6398.546  6449.288  6469.3    6524.68    217.178   227.742   254.884
   261.35    327.696   275.098   274.622   286.208   290.108   335.49
 14960.24  15016.15  15597.864 16474.42  16844.014  1316.388  1350.052
  1447.644  1509.756  1569.662   629.366   610.542   589.634   611.922
   716.504  4831.41   4766.216  4701.424  4641.544  4612.1    5693.634
  5661.866  5615.52   5602.32   5589.12   5344.23   5369.79   5484.35
  5585.706  5662.19   1858.798  1840.47   1849.628  1973.1    2034.34
  1937.52   1911.526  1879.152  1867.682  1848.048   816.188   812.506
   822.508   835.294   916.932 13067.976 13336.772 13681.908 14075.546
 14386.68   4740.376  4900.45   4967.924  4998.03   5044.22   2880.278
  2866.826  2876.92   2891.77   2961.18   2464.17   2457.944  2437.482
  2444.222  2475.926  2762.624  2799.784  2848.028  2866.646  2904.606
  3236.952  3285.528  3338.354  3430.826  3538.056   926.194   929.116
   894.776   909.192  1392.208  4094.378  4059.416  4009.14   3953.48
  3933.782]

In [ ]:
len(y_pred)

295

In [ ]:
df1 = df1.assign(ImmatricolazioniPredette=y_pred)

In [ ]:
df1

,AnnoAccademico,Ateneo,PopolazioneP,AteneiP,PopolazioneR,AteneiR,FuoriSede,Immatricolati,ImmatricolazioniPredette
0,2021/2022,Aosta,123041,1,123704,1,77,246,191.412
1,2022/2023,Aosta,122745,1,123408,1,81,248,188.846
2,2023/2024,Aosta,122449,1,123112,1,85,250,185.276
3,2024/2025,Aosta,122153,1,122816,1,89,252,185.746
4,2025/2026,Aosta,121857,1,122520,1,93,254,191.522
...,...,...,...,...,...,...,...,...,...
290,2021/2022,Verona,929582,1,4870663,4,2545,4695,4094.378
291,2022/2023,Verona,932056,1,4871326,4,2543,4672,4059.416
292,2023/2024,Verona,934530,1,4871989,4,2541,4649,4009.140
293,2024/2025,Verona,937004,1,4872652,4,2539,4626,3953.480
294,2025/2026,Verona,939478,1,4873315,4,2537,4603,3933.782

In [ ]:
df1.to_excel("/content/drive/MyDrive/KPMG/Risultato_regressione_finale.xlsx", sheet_name="Risultati", index=False)